name: 'african_market_intelligence'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'african_market_intelligence'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
models:
  african_market_intelligence:
    # Config indicated by + and applies to all files under models/staging/
    staging:
      +materialized: view
    
    # Business marts (tables)
    marts: 
      +materialized: table
      dimensions:
        +materialized: table
      facts: 
        +materialized: table
